language: node_js
node_js:
- '11'
script:
- npm test
- npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: bash tools/deploy.sh --repo="https://deploybot:$GIT_TOKEN_DEPLOY_MASTER@github.com/logolang/logolang.github.io.git" --branch="master" --message="Deployment"
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash tools/deploy.sh --repo="https://deploybot:$GIT_TOKEN_DEPLOY_MASTER@github.com/megaboich/logo-playground-stage.git" --branch="gh-pages" --message="Deployment"
    on:
      branch: stage